### ISSUE TITLE
What about docs ?

### ISSUE THREAD

**Issue by amaanlari** [amaanlari/github-projects-playground#6]
Let's work on the documentation with @amaan-lari  suggestions:
- [x] #7
- [x] #8
- [x] #9
- [x] Decide if we want to go with something more complex

**Comment by amaan-lari** [comment]
Why don't we start as easily as possible with just a sample doc folder with a single markdown document, then turn on GIthub pages and point to it, we can decide if we want to go with something more complex like Jekyll or Eleventy later.

**Comment by amaanlari** [comment]
So what you're saying is that we should
- [ ] Create a `docs` folder
- [ ] Create a new `index.md` file
- [ ] Turn on Github Pages
- [ ] Decide if we want to go with something more complex

**Comment by amaanlari** [comment]
Thanks @amaan-lari  I created the issues for the first three suggestions, if you think of anything else, let me know.
